name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true

jobs:
  build:
    name: Build and Release for win-x64
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore SDDLConvertDomain.sln

      - name: Build the solution
        run: msbuild SDDLConvertDomain.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Archive the build
        uses: actions/upload-artifact@v3
        with:
          name: SDDLConvertDomain-win-x64
          path: |
            SDDLConvertDomainConsole\bin\Release\**

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: SDDLConvertDomainConsole/bin/Release/**
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name || github.ref_name }}
          name: Release ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name || github.ref_name }}
          draft: false
          prerelease: false
