name: Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true

jobs:
  build:
    name: Build and Release for win-x64
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore SDDLConvertDomain.sln

      - name: Build the solution
        run: msbuild SDDLConvertDomain.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Create ZIP archive
        run: |
          mkdir artifacts
          $tag = "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name || github.ref_name }}"
          Write-Output "Tag is: $tag"
          Compress-Archive -Path SDDLConvertDomainConsole\bin\Release\* -DestinationPath "artifacts\SDDLConvertDomain-win-x64-$tag.zip"


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SDDLConvertDomain-win-x64-$tag.zip
          path: artifacts\SDDLConvertDomain-win-x64-*.zip

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts\SDDLConvertDomain-win-x64-*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name || github.ref_name }}
          name: Release ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name || github.ref_name }}
          draft: false
          prerelease: false
